### ISSUE TITLE
Satscard::Satscard() succeeds when communicating with a Tapsigner

### ISSUE THREAD

**Issue by PeteClubSeven** [nunchuk-io/tap-protocol#6]
Hey, not sure how much you consider this to be an issue but I wanted to test what would happen if the user gave my library invalid input (saying they want a Satscard but scanning a Tapsigner and vice versa). Interesting if you try to construct a Tapsigner and the transport communicates with a physical Satscard an exception will be thrown when validating the certificates. When you try to construct a Satscard out of a Tapsigner however, it succeeds despite is_tapsigner_ being true and it having no address.

This isn't a super pressing issue, I'll just validate the cards by checking is_tapsigner_ == false but it might be worth adding extra error checking at some point 👍

**Comment by nogibi** [comment]
Thanks for reporting, fixed in #7.

**Comment by PeteClubSeven** [comment]
Amazing thanks a lot!
